### PR TITLE
Gas Schedule DGP implementation (Qtum Core / QTUMCORE-60)

### PR DESCRIPTION
**Pull request by designsters**
1. Created a new qtum genesis files.
2. Added qtumMainNetwork.
3. Created class QtumDGP.
4. Implemented QtumDGP to qtum.

### CODE REVIEW

**Comment by Earlz** [comment]
@designsters Can you rebase this so that it can be merged into master soon?

**Comment by qtum-neil** [comment]
Please fix this warning:

```
qtum/qtumDGP.cpp:112:33: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        schedule.tierStepGas = {uint32Values[0], uint32Values[1], uint32Values[2], uint32Values[3],
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by qtum-neil** [comment]
also these:
```
test/qtumtests/dgp_tests.cpp:276:71: warning: suggest braces around initialization of subobject [-Wmissing-braces]
EVMScheduleCustom EVMScheduleContractGasSchedule(true,true,true,true,{10,10,10,10,10,10,10,10},10,50,30,6,200,20000,5000,15000,
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                                                      {                      }
test/qtumtests/dgp_tests.cpp:278:72: warning: suggest braces around initialization of subobject [-Wmissing-braces]
EVMScheduleCustom EVMScheduleContractGasSchedule2(true,true,true,true,{13,10,10,10,10,10,10,10},10,50,30,6,200,20000,5000,15000,
                                                                       ^~~~~~~~~~~~~~~~~~~~~~~
                                                                       {                      }
test/qtumtests/dgp_tests.cpp:280:72: warning: suggest braces around initialization of subobject [-Wmissing-braces]
EVMScheduleCustom EVMScheduleContractGasSchedule3(true,true,true,true,{13,13,10,10,10,10,10,10},10,50,30,6,200,20000,5000,15000,
                                                                       ^~~~~~~~~~~~~~~~~~~~~~~
                                                                       {                      }
test/qtumtests/dgp_tests.cpp:350:16: warning: comparison of constant 569 with expression of type 'bool' is always false [-Wtautological-constant-out-of-range-compare]
    if(618 > i > 569)
       ~~~~~~~ ^ ~~~
test/qtumtests/dgp_tests.cpp:352:16: warning: comparison of constant 518 with expression of type 'bool' is always false [-Wtautological-constant-out-of-range-compare]
    if(568 > i > 518)
       ~~~~~~~ ^ ~~~
test/qtumtests/dgp_tests.cpp:354:16: warning: comparison of constant 502 with expression of type 'bool' is always false [-Wtautological-constant-out-of-range-compare]
    if(518 > i > 502) // After initializing the tests, the height of the chain 502
       ~~~~~~~ ^ ~~~

```

**Comment by qtum-neil** [comment]
@designsters please also update MAX_BLOCK_SERIALIZED_SIZE and the MAX_PROTOCOL_MESSAGE_LENGTH

**Pull request merged**
