### PR TITLE
Upgrade to Constantinople EVM

### PR DESCRIPTION
**Pull request by timemarkovqtum**
The activation block height for the Constantinople can be set using the parameter `consensus.QIP7Height` in the file `chainparams.cpp`.

### CODE REVIEW

**Comment by hayeah** [comment]
how much work would it be to upgrade to byzantium? @timemarkovqtum 

the "revert reason" would be very helpful. see: https://github.com/qtumproject/qips/issues/8#issuecomment-490370253

**Comment by qtum-neil** [comment]
> how much work would it be to upgrade to byzantium? @timemarkovqtum
> 
> the "revert reason" would be very helpful. see: [qtumproject/qips#8 (comment)](https://github.com/qtumproject/qips/issues/8#issuecomment-490370253)

This already includes Byzantium.

**Comment by hayeah** [comment]
@qtum-neil how is revert reason exposed to the outside world? I don't see it in transaction receipt.

**Comment by timemarkovqtum** [comment]
According to `eip-140`, the `REVERT` instruction is active `block.number >= BYZANTIUM_FORK_BLKNUM`, which mean active Byzantium fork or above, Constantinople fork is above Byzantium, so it should work there too. There is no mentions in `eip-140` that it is removed in the next forks.

**Comment by qtum-neil** [comment]
Merged here: https://github.com/qtumproject/qtum/pull/736

**Pull request closed without merging**
