### PR TITLE
waitforlogs RPC long-polling, and client-close detection

### PR DESCRIPTION
**Pull request by hayeah**
This PR adds the waitforlogs RPC call, as documented below.

# Long-Polling Client Liveness

It also extends bitcoin's JSON RPC server to support long-polling better. In a long-polling request, we want a request handling thread to terminate as soon as the remote client closes the TCP connection. 

This is accomplished by activating chunk-transferring mode for long-poll JSON requests. When `PollAlive` is called, an empty space is sent to the client. A write to the underlying connection can reliably detect connection close for different versions of libevent. When the result is ready for a long-poll request, dump the final JSON result as the last chunk of the request.

See commit:

https://github.com/qtumproject/qtum/commit/d31571c477b95113a6328f2545c1d9f6e5b2655f

# waitforlogs

waitforlogs (fromBlock) (toBlock) (filter) (timeout)

Waits for a new logs and return matching log entries. When the call returns, it also specifies the next block number to start waiting for new logs.

By calling waitforlogs repeatedly using the returned `nextBlock` number, a client can receive a stream of up-to-date log entires.

## Arguments
1. fromBlock (int | "latest", optional, default="latest") The block number to start looking for logs. ()
2. toBlock   (int | "latest", optional, default=null) The block number to start looking for logs. If null, will wait indefinitely into the future.
3. filter    ({ addresses?: Hex160String[], topics?: Hex256String[] }, optional default={}) Filter conditions for logs. Addresses and topics are specified as array of hexadecimal strings

## Result

An object with the following properties:
1. logs (LogEntry[]) Array of matchiing log entries. This may be empty if `filter` removed all entries.
2. count (int) How many log entries are returned.
3. nextBlock (int) To wait for new log entries haven't seen before, use this number as `fromBlock`
Usage:

`waitforlogs` waits for new logs, starting from the tip of the chain.
`waitforlogs 600` waits for new logs, but starting from block 600. If there are logs available, this call will return immediately.
`waitforlogs 600 700` waits for new logs, but only up to 700th block
`waitforlogs '"latest"' null` this is equivalent to `waitforlogs`, using default parameter values
`waitforlogs '"latest"' null` { "addresses": [ "ff0011..." ], "topics": [ "c0fefe"] }` waits for logs in the future matching the specified conditions

Sample Output:

```
{
  "entries": [
    {
      "blockHash": "56d5f1f5ec239ef9c822d9ed600fe9aa63727071770ac7c0eabfc903bf7316d4",
      "blockNumber": 3286,
      "transactionHash": "00aa0f041ce333bc3a855b2cba03c41427cda04f0334d7f6cb0acad62f338ddc",
      "transactionIndex": 2,                                                                                                                                                               "from": "3f6866e2b59121ada1ddfc8edc84a92d9655675f",
      "to": "8e1ee0b38b719abe8fa984c986eabb5bb5071b6b",
      "cumulativeGasUsed": 23709,
      "gasUsed": 23709,
      "contractAddress": "8e1ee0b38b719abe8fa984c986eabb5bb5071b6b",                                                                                                                       "topics": [
        "f0e1159fa6dc12bb31e0098b7a1270c2bd50e760522991c6f0119160028d9916",
        "0000000000000000000000000000000000000000000000000000000000000002"
      ],
      "data": "00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000003"
    }
  ],

  "count": 7,
  "nextblock": 801
}
```

### CODE REVIEW

**Comment by Earlz** [comment]
Does this rely on a specific version of libevent?

**Comment by Earlz** [comment]
It seems to not work with Gitian builds. Are there new dependencies needed in configure.ac?

`libbitcoin_server.a(libbitcoin_server_a-httpserver.o): In function `InitHTTPServer()':                      /home/ubuntu/build/qtum/distsrc-i686-pc-linux-gnu/src/httpserver.cpp:405: undefined reference to `evthread_use_pthreads' `

**Comment by hayeah** [comment]
@Earlz hm I didn't make changes to `InitHTTPServer`. I am just libevents2, as the RPC server already is.

**Comment by hayeah** [comment]
fixed another racing condition where the HTTP even loop terminates immediately when the process receives SIGTERM. 

The event-loop terminating early locks up the long-poll thread because it's waiting for the loop to complete the request.

**Comment by hayeah** [comment]
I fixed the build problem on Linux by adding to `EVENT_PTHREADS_LIBS` to `test_test_qtum_LDADD`.

But I am not entirely sure why the build worked before.

The method that made the `evthread_use_pthreads` was there since the very beginning (3 years ago).

https://github.com/qtumproject/qtum/blame/1a926b980f03e97322c7dd787835bec1730f35d2/src/httpserver.cpp#L405

Maybe compiler optimization pruned away the offending call `InitHTTPServer` in test, but some of my changes made that impossible?

**Comment by Earlz** [comment]
Linux looks to build now (needs testing to ensure no dynamic library dependency) but Windows now has a problem:

```
  CXX      rpc/libbitcoin_server_a-misc.o
rpc/blockchain.cpp:1113:1: error: ‘uint’ does not name a type
 uint parseUInt(const UniValue& val, uint defaultVal) {
 ^
rpc/blockchain.cpp:1126:1: error: ‘uint’ does not name a type
 uint parseBlockHeight(const UniValue& val) {
 ^
rpc/blockchain.cpp:1150:1: error: ‘uint’ does not name a type
 uint parseBlockHeight(const UniValue& val, uint defaultVal) {
 ^
rpc/blockchain.cpp: In constructor ‘WaitForLogsParams::WaitForLogsParams(const UniValue&)’:
rpc/blockchain.cpp:1246:71: error: ‘parseBlockHeight’ was not declared in this scope
         fromBlock = parseBlockHeight(params[0], latestblock.height + 1);
                                                                       ^
rpc/blockchain.cpp:1250:41: error: ‘parseUInt’ was not declared in this scope
         minconf = parseUInt(params[3], 6);
                                         ^
rpc/blockchain.cpp: In constructor ‘SearchLogsParams::SearchLogsParams(const UniValue&)’:
rpc/blockchain.cpp:1427:41: error: ‘parseUInt’ was not declared in this scope
         minconf = parseUInt(params[4], 0);
                                         ^
rpc/blockchain.cpp: In member function ‘void SearchLogsParams::setFromBlock(const UniValue&)’:
rpc/blockchain.cpp:1433:45: error: ‘parseBlockHeight’ was not declared in this scope                                                           
             fromBlock = parseBlockHeight(val);
                                             ^
rpc/blockchain.cpp: In member function ‘void SearchLogsParams::setToBlock(const UniValue&)’:
rpc/blockchain.cpp:1441:43: error: ‘parseBlockHeight’ was not declared in this scope
             toBlock = parseBlockHeight(val);
```

**Pull request merged**
